version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "16:16"
  open-pull-requests-limit: 10
  reviewers:
  - altcoder
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  commit-message:
    prefix: "fix: "
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "16:32"
  commit-message:
    prefix: "fix: "
