name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    uses: altcoder/action-python/.github/workflows/validation.yml@v0.1
    with:
      workdir: '.'
      testdir: 'tests'
